name: Stories of Sonnet
favicon: null
layout_spectrum: 0.1510523788165301
typography_spectrum: 0.6166974527295679
title: Stories of Sonnet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77461390-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e9e9'
    - '#414141'
    - '#cede00'
    - '#a1ac14'
    - '#130e12'
  brandStrength: 0.8533553008455783
  lightness: 0.030091490363702178
  saturation: 0.7634687258396298
  rhythmicContrast: 0.16055571078322828
purpose: []
