name: Stories of Sonnet
favicon: null
layout_spectrum: 0.57263
typography_spectrum: 0.26277
title: 'Sonnet: redesigning insurance'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77461390-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e9e9'
    - '#414141'
    - '#cede00'
    - '#a1ac14'
    - '#130e12'
  brandStrength: 0.1875
  lightness: 0.030091490363702178
  saturation: 0.625
  rhythmicContrast: 0.16055571078322828
purpose: []
